### ISSUE TITLE
Address set to x48 

### ISSUE THREAD

**Issue by meeki007** [felixdrp/ads1x15#1]
I'm running 2 ads1115's wondering if you can expand the options to allow selection of addresses x48, x49, x4A, and x4B ???

the same way you change the i2c bus with
```
await adc.openBus(1);
```
but maybe 
```
await adc.address(x49);
```
????

**Comment by felixdrp** [comment]
Hello,
I added setAddress to the last update.
try:
adc.setAddress(0x49)

Also you could try directly:
adc.address = 0x49

Thank you

**Comment by meeki007** [comment]
I took the time to read through your code ...... Its rather nice and concise.... and that makes it hard without documentation to understand how to play with it. I never bothered playing with ES6 Destructuring Assignment inside of function parameters. Learned allot :) 

Would you be interested in a pull request updating the documentation ? I'd like to show examples for setting the programmable_gain_amplifier and the  samples_per_second.

**I'd format this correct for your documentation** but here is a code snippet of how I worked it out.
```
const channels_array_of_objects = [
              {channel: 0, programmable_gain_amplifier: 2048, samples_per_second: 250},
              {channel: 1, programmable_gain_amplifier: 2048, samples_per_second: 250},
              {channel: 2, programmable_gain_amplifier: 2048, samples_per_second: 250},
              {channel: 3, programmable_gain_amplifier: 2048, samples_per_second: 250}
              //{p: 2, n: 3},
            ];

            //notify_user_errors('Reading Single shot:');
            for await (let request of channels_array_of_objects) {
              try {
                voltage_output_object[format_i2c_device_number][format_number_of_chip][format_number_of_i2c_address][format_inputsForChannel]['channel_'+request.channel] = {};
                const measure = await adc.readSingleEnded({
                  channel: request.channel,
                  pga: request.programmable_gain_amplifier,
                  sps: request.samples_per_second
                });
                //notify_user_errors("request.channel="+request.channel);
                voltage_output_object[format_i2c_device_number][format_number_of_chip][format_number_of_i2c_address][format_inputsForChannel]['channel_'+request.channel]['Volts'] = measure / 1e3;
                voltage_output_object[format_i2c_device_number][format_number_of_chip][format_number_of_i2c_address][format_inputsForChannel]['channel_'+request.channel]['miliVolts'] = measure;

              } catch (error) {
                notify_user_errors(error);
              }
            }
```

**Comment by felixdrp** [comment]
Hello meeki007,

> Would you be interested in a pull request updating the documentation ?

Yes, please.

I would like the community to have a place to share examples, so I opened the wiki.
Please, add a link to your example at the wiki.

Cheers,

**Comment by meeki007** [comment]
Awesome! Busy at work at the moment. Give me a week or 2 and I'll add some
documentation.
Thanks for opening the wiki. Feel free to close this issue if ya like.

Thanks again Felix
